version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    command: ["--replSet", "${MONGO_REPLSET_NAME}", "--port", "${MONGO_PORT}", "--keyFile", "/data/key.file"]
    restart: always
    ports:
      - 27017:${MONGO_PORT}
    volumes:
      - ./mongo/initdb.d/:/docker-entrypoint-initdb.d/
      - ./mongo/init-replicaSet.sh:/data/init-replicaSet.sh:ro
      - ./mongo/key.file:/data/key.file:ro
      - mongodbdata:/data/db
    env_file: .env
    networks:
      - db

  elasticsearch:
    env_file: .env
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearchdata
        target: /usr/share/elasticsearch/data
    networks:
      - elk
  
  kibana:
    env_file: .env
    image: kibana:7.8.1
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - 5601:5601
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    networks:
      - elk
    depends_on:
      - elasticsearch

  monstache:
    env_file: .env
    image: rwynn/monstache:latest
    container_name: monstache
    # command: -f /config.toml
    command: tail -F anything
    volumes:          
      - monstachedata:/monstache/
      - type: bind
        source: ./monstache/config.toml
        target: /config.toml
        read_only: true
    ports:
      - "8080:8080"
    networks:
      - db
      - elk
    depends_on:
      - elasticsearch
      - mongodb

networks:
  db:
    driver: bridge
  elk:
    driver: bridge

volumes:
  mongodbdata:
  elasticsearchdata:
  monstachedata: