version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    command: ["--replSet", "${MONGO_REPLSET_NAME}", "--port", "${MONGO_PORT}", "--keyFile", "/data/key.file"]
    restart: always
    healthcheck:
      test: |
        test $$(sh /data/init-replicaSet.sh) -eq 1
      interval: 10s
      start_period: 30s
    ports:
      - 27017:${MONGO_PORT}
    volumes:
      - ./mongo/initdb.d/:/docker-entrypoint-initdb.d/
      - ./mongo/init-replicaSet.sh:/data/init-replicaSet.sh:ro
      - ./mongo/key.file:/data/key.file:ro
      - mongodbdata:/data/db
    env_file: .env
    networks:
      - db

  elasticsearch:
    env_file: .env
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearchdata
        target: /usr/share/elasticsearch/data
    networks:
      - elk
  
  kibana:
    env_file: .env
    environment:
      - ELASTICSEARCH_HOSTS=http://${ELASTIC_USER}:${ELASTIC_PASSWORD}@elasticsearch:9200
    image: kibana:7.8.1
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - 5601:5601
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    networks:
      - elk
    depends_on:
      - elasticsearch

  monstache:
    env_file: .env
    environment:
      - MONSTACHE_ES_USER=${ELASTIC_USER}
      - MONSTACHE_ES_PASS=${ELASTIC_PASSWORD}
      - MONSTACHE_MONGO_URL=mongodb://${MONGO_INITDB_USER}:${MONGO_INITDB_PWD}@mongodb:${MONGO_PORT}
    image: rwynn/monstache:latest
    container_name: monstache
    # command: -f /config.toml
    # command: tail -F anything
    volumes:          
      - monstachedata:/monstache/
    networks:
      - db
      - elk
    depends_on:
      - elasticsearch
      - mongodb

networks:
  db:
    driver: bridge
  elk:
    driver: bridge

volumes:
  mongodbdata:
  elasticsearchdata:
  monstachedata: