server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
elasticsearch.username: elastic
elasticsearch.password: elasticpass
xpack.monitoring.ui.container.elasticsearch.enabled: true
